# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true

env:
  - NOT_CRAN=true

r_packages:
  - devtools

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      r: devel
    - os: linux
      dist: trusty
      sudo: false
      r: release
    - os: linux
      dist: trusty
      sudo: false
      r: oldrel
    - os: osx
      osx_image: xcode8
      r: release


branches:
  only:
    - master
    - develop

after_success:
  - Rscript -e 'covr::codecov()'
