# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
cran: https://cloud.r-project.org

env:
  - NOT_CRAN=true

r_packages:
  - devtools

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      r: devel
    - os: linux
      dist: bionic
      sudo: false
      r: release
    - os: linux
      dist: bionic
      sudo: false
      r: oldrel
#    - os: osx
#      osx_image: xcode8
#      r: release

before_install:
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev

script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check rsinaica*tar.gz
  # The most polluted cities articles take a long time to run, so exclude 'em
  - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > ~/.Rprofile
  - mv vignettes/articles/ozone_awards.Rmd vignettes/articles/_ozone_awards.Rmd
  - mv vignettes/articles/pm10_awards.Rmd vignettes/articles/_pm10_awards.Rmd
  - mv vignettes/articles/pm25_awards.Rmd vignettes/articles/_pm25_awards.Rmd
  - mv vignettes/articles/trends.Rmd vignettes/articles/_trends.Rmd
  - mv vignettes/articles/covid.Rmd vignettes/articles/_covid.Rmd
  - rm -rf docs/*
  - travis_wait 40 Rscript -e "tryCatch({install.packages('remotes');remotes::install_github('r-lib/pkgdown');remotes::install_github('diegovalle/rsinaica');pkgdown::build_site()}, error = function(e) {quit(status=1)})"

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'
