# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
cran: https://cloud.r-project.org

env:
  - NOT_CRAN=true

r_packages:
  - devtools

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      r: devel
    - os: linux
      dist: trusty
      sudo: false
      r: release
    - os: linux
      dist: trusty
      sudo: false
      r: oldrel
#    - os: osx
#      osx_image: xcode8
#      r: release

after_success:
  # The most polluted cities articles take a long time to run, so exclude 'em
  - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > ~/.Rprofile
  - mv vignettes/articles/ozone_awards.Rmd vignettes/articles/_ozone_awards.Rmd
  - mv vignettes/articles/pm10_awards.Rmd vignettes/articles/_pm10_awards.Rmd
  - mv vignettes/articles/pm25_awards.Rmd vignettes/articles/_pm25_awards.Rmd
  - mv vignettes/articles/trends.Rmd vignettes/articles/_trends.Rmd
  - Rscript -e "tryCatch({install.packages('remotes');remotes::install_github('r-lib/pkgdown');remotes::install_github('diegovalle/rsinaica');pkgdown::build_site()}, error = function(e) {quit(status=1)})"
  - Rscript -e 'covr::codecov()'
