---
title: "Most PM10 Polluted City in Mexico"
author: "Diego Valle-Jones"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



Load the packages

```{r packages,warning=FALSE,message=FALSE}
## Auto-install required R packages
packs <- c("dplyr", "ggplot2", "gghighlight", "lubridate", "anomalize")
success <- suppressWarnings(sapply(packs, require, character.only = TRUE))
if (length(names(success)[!success])) {
  install.packages(names(success)[!success])
  sapply(names(success)[!success], require, character.only = TRUE)
}
## Not yet on cran
library("rsinaica")
```

```{r download_pm10, cache=TRUE}
# Download all PM10 pollution data in 2017
pm10_2017 <- bind_rows(
  mapply(sinaica_byparameter,
         "PM10",
         seq(as.Date("2017-01-01"), as.Date("2017-12-01"), by = "month"),
         seq(as.Date("2017-02-01"), as.Date("2018-01-01"), by = "month") - 1,
         SIMPLIFY = FALSE)
)
       
```


```{r manual}
# Download all manually collected PM10 pollution data in 2017
pm10_2017m <- bind_rows(
  mapply(sinaica_byparameter,
         "PM10",
         seq(as.Date("2017-01-01"), as.Date("2017-12-01"), by = "month"),
         seq(as.Date("2017-02-01"), as.Date("2018-01-01"), by = "month") - 1,
         "Manual",
         SIMPLIFY = FALSE)
)
pm10_2017 = bind_rows(pm10_2017, pm10_2017m)       
```

```{r}
knitr::kable(head(pm10_2017))
```


```{r plot}
# pm10_2017[which(pm10_2017$value_actual != pm10_2017$value_original),]
# pm10_2017[which(!is.na(pm10_2017$date_validated)),]

# Only include stations that reported for more than 80% of days (292)
df_filtered <- pm10_2017 %>%
  filter(!is.na(value)) 

df_filtered %>%
  group_by(network_name) %>%
  summarise(count = n()) %>%
  arrange(count) %>%
  head(10) %>%
  knitr::kable()


df_max <- df_filtered %>%
  group_by(date, station_id, network_name) %>%
  summarise(mean = mean(value, na.rm = TRUE)) %>%
  group_by(date, network_name) %>%
  summarise(max = max(mean, na.rm = TRUE)) %>%
  ungroup() %>%
  add_count(network_name) %>%
  filter(n > (365*.8))  %>%
  select(-n) %>%
  arrange(date)
```

```{r, fig.widht = 8, fig.height = 18}
ggplot(df_max, aes(as.Date(date), max)) +
  geom_line(size = .3, color = "black") +
  facet_wrap(~ network_name, ncol = 3) +
  ggtitle("Maximum daily ozone concentration by network") +
  xlab("date") +
  ylab("daily maximum hourly ozone concentration (ppm)") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=60,hjust=1))

df_max <- df_max %>%
  ungroup() %>%
  group_by(network_name) %>%
  mutate(date = as.Date(date)) %>%
  time_decompose(max, method = "stl") %>%
  anomalize(remainder, method = "gesd", alpha = 0.0001) %>%
  time_recompose()


# Anomaly Visualization
df_max %>% plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.25) +
  labs(title = "Tidyverse Anomalies", subtitle = "STL + GESD Methods") 

#df_max <- filter(df_max, anomaly != "Yes")
```

```{r}

gghighlight_line(df_max, aes(as.Date(date), observed, 
                              group = network_name, color = network_name),
                 mean(observed, na.rm = TRUE), max_highlight = 1) +
  theme_bw() +
  ggtitle(expression(paste("Pollution measuring network with highest average maximum ", 
                           PM[10], " pollution values in 2017"))) +
  xlab("date") +
  ylab(expression(paste("daily maximum 24 average of ", PM[10], 
                        " (", mu,"g/", m^3, ")")))
```


```{r plotly, warning=FALSE, message=FALSE, fig.width = 10, fig.height = 4}
library("plotly")
library("tidyr")
library("zoo")

top3 <- filter(df_max, network_name %in% c("Toluca",
                                           "Guadalajara",
                                           "Monterrey"))[, 1:3]

top3 <- spread(top3, network_name, observed)
top3$date <- as.Date(as.Date(top3$date))
top3$Toluca <- na.spline(top3$Toluca)
top3$Guadalajara <- na.spline(top3$Guadalajara)
top3$Monterrey <- na.spline(top3$Monterrey)
x <- list(
  title = "date"
)
y <- list(
  title = "daily maximum 24 average of PM10"
)

plot_ly(as.data.frame(top3), x = ~date, y = ~Monterrey, name = "Monterrey" ,
        type = 'scatter', mode = 'lines', line = list(color = '#e41a1c'), width = .5) %>%
  add_trace(y = ~Guadalajara, name = 'Guadalajara', mode = 'lines', line = list(color = '#377eb8'), width = .5) %>%
  add_trace(y = ~Toluca, name = 'Toluca', mode = 'lines', line = list(color = '#4daf4a'), width = .5) %>%
  layout(title = "Top 3 most PM10-polluted cities in Mexico", xaxis = x, yaxis = y)
```
```{r}
df_max %>%
  group_by(network_name) %>%
  filter(observed > 75.5) %>%
  summarise(count = n()) %>%
  arrange(-count) %>%
  head() %>%
  knitr::kable()

df_max %>%
  group_by(network_name) %>%
  filter(observed > 215.5) %>%
  summarise(count = n()) %>%
  arrange(-count) %>%
  head() %>%
  knitr::kable()

```
