---
title: "Most PM2.5 Polluted City in Mexico"
author: "Diego Valle-Jones"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



First, load the packages

```{r packages,warning=FALSE,message=FALSE}
## Auto-install required R packages
packs <- c("dplyr", "ggplot2", "gghighlight", "lubridate", "anomalize", 
           "zoo", "tidyr")
success <- suppressWarnings(sapply(packs, require, character.only = TRUE))
if (length(names(success)[!success])) {
  install.packages(names(success)[!success])
  sapply(names(success)[!success], require, character.only = TRUE)
}
## Not yet on cran
library("rsinaica")
```

```{r download_pm25, cache=TRUE}
# Download all PM25 pollution data in 2017
pm25_2017 <- bind_rows(
  mapply(sinaica_param_data,
         "PM2.5",
         seq(as.Date("2017-01-01"), as.Date("2017-12-01"), by = "month"),
         seq(as.Date("2017-02-01"), as.Date("2018-01-01"), by = "month") - 1,
         SIMPLIFY = FALSE)
)
       
```

```{r}
bind_rows(
  mapply(sinaica_param_data,
         "PM2.5",
         seq(as.Date("2017-01-01"), as.Date("2017-12-01"), by = "month"),
         seq(as.Date("2017-02-01"), as.Date("2018-01-01"), by = "month") - 1,
         "Manual",
         SIMPLIFY = FALSE)
)
```

```{r}
knitr::kable(head(pm25_2017))
```


```{r plot}
# pm25_2017[which(pm25_2017$value_actual != pm25_2017$value_original),]
# pm25_2017[which(!is.na(pm25_2017$date_validated)),]

pm25_2017 %>%
  mutate(value = ifelse(value < 3, NA, value)) %>%
  group_by(network_name) %>%
  filter(!is.na(value)) %>%
  summarise(count = n_distinct(week(date))) %>%
  arrange(count) %>%
  head(10) %>%
  knitr::kable()

## filter stations that didn't report at least 47 weeks of the year
df_filtered <- pm25_2017 %>%
  #filter(value < 250) %>%
  mutate(value = if_else(value < 1, NA_real_, value)) %>%
  group_by(network_name) %>%
  filter(!is.na(value)) %>%
  mutate(nweeks = n_distinct(week(date))) %>%
  filter(nweeks >= 47) %>%
  select(-nweeks) %>%
  ungroup()



df_max <- df_filtered %>%
  complete(station_id,
           hour = 0:23,
           date = as.character(seq(as.Date("2017-01-01"), as.Date("2017-12-31"), by = "day"))) %>%
  group_by(station_id, network_name) %>%
  arrange(station_id, date, hour) %>%
  mutate(roll24 = rollapply(value, 24, mean, na.rm = TRUE, partial = 18, 
                            fill = NA, align = "right")) %>%
  ungroup() %>%
  #summarise(mean = mean(value, na.rm = TRUE)) %>%
  group_by(date, network_name) %>%
  summarise(max = max(roll24, na.rm = TRUE)) %>%
  ungroup() %>%
  add_count(network_name) %>%
  ## Only include stations that reported for more than 80% of days (292)
  filter(n >= (365*.8))  %>%
  select(-n) %>%
  filter(is.finite(max)) %>%
  arrange(date)
```

```{r, fig.widht = 8, fig.height = 18}
ggplot(df_max, aes(as.Date(date), max)) +
  geom_line(size = .3, color = "black") +
  facet_wrap(~ network_name, ncol = 3) +
  ggtitle(expression(paste("Maximum daily ", PM[2.5], " concentration by network"))) +
  xlab("date") +
  ylab(expression(paste("daily maximum 24 average of ", PM[2.5], 
                        " (", mu,"g/", m^3, ")"))) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=60,hjust=1))

df_max <- df_max %>%
  ungroup() %>%
  group_by(network_name) %>%
  mutate(date = as.Date(date)) %>%
  time_decompose(max, method = "stl") %>%
  anomalize(remainder, method = "gesd", alpha = 0.0001) %>%
  time_recompose()


# Anomaly Visualization
df_max %>% plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.25) +
  labs(title = "Tidyverse Anomalies", subtitle = "STL + GESD Methods") 

#df_max <- filter(df_max, anomaly != "Yes")
df_max <- filter(df_max, !network_name %in% c("Aguascalientes", "Irapuato",
                                             "Torreón"))
```

It was decided to remove Irapuato from the rankings and keep Oaxaca and Tepic becuase PM<sub>2.5</sub> values can spike because of fires.

```{r}
df_max <- filter(df_max, !network_name %in% c("Irapuato"))
gghighlight_line(df_max, aes(as.Date(date), observed, 
                              group = network_name, color = network_name),
                 mean(observed, na.rm = TRUE), max_highlight = 1) +
  theme_bw() +
  ggtitle(expression(paste("Pollution measuring network with highest average maximum ", 
                           PM[2.5], " pollution values in 2017"))) +
  xlab("date") +
  ylab(expression(paste("daily maximum 24 average of ", PM[2.5], 
                        " (", mu,"g/", m^3, ")")))
```


```{r plotly, warning=FALSE, message=FALSE, fig.width = 10, fig.height = 4}
library("plotly")
library("tidyr")
library("zoo")

top3 <- filter(df_max, network_name %in% c("Toluca",
                                           "Pachuca",
                                           "Guadalajara"))[, 1:3]

top3 <- spread(top3, network_name, observed)
top3$date <- as.Date(as.Date(top3$date))
top3$Toluca <- na.spline(top3$Toluca)
top3$Guadalajara <- na.spline(top3$Guadalajara)
top3$Pachuca <- na.spline(top3$Pachuca)
x <- list(
  title = "date"
)
y <- list(
  title = "daily maximum 24 average of PM2.5"
)

plot_ly(as.data.frame(top3), x = ~date, y = ~`Toluca`, name = "Toluca" ,
        type = 'scatter', mode = 'lines', line = list(color = '#e41a1c'), width = .5) %>%
  add_trace(y = ~Pachuca, name = 'Pachuca', mode = 'lines', line = list(color = '#377eb8'), width = .5) %>%
  add_trace(y = ~Guadalajara, name = 'Guadalajara', mode = 'lines', line = list(color = '#4daf4a'), width = .5) %>%
  layout(title = "Top 3 most PM2.5-polluted cities in Mexico", xaxis = x, yaxis = y)
```
```{r}
df_max %>%
  group_by(network_name) %>%
  filter(observed > 45.05) %>%
  summarise(count = n()) %>%
  arrange(-count) %>%
  head() %>%
  knitr::kable()

df_max %>%
  group_by(network_name) %>%
  filter(observed > 97.45) %>%
  summarise(count = n()) %>%
  arrange(-count) %>%
  head() %>%
  knitr::kable()

```
