# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '7 20 * * 5'
  push:
    branches:
      - main
      - master
      - develop
      - test
  pull_request:
    branches:
      - main
      - master
      - develop
      - test

name: R-CMD-check.yaml

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Trigger / Branch    ubuntu (all versions)	windows-latest	macos-latest
# Push to main/master	✅ Runs               ✅ Runs         ✅ Runs
# Push to test  	    ✅ Runs               ✅ Runs         ✅ Runs
# Push to develop	    ✅ Runs               ❌ Skipped      ❌ Skipped
# Weekly Schedule	    ✅ Runs (release)     ❌ Skipped      ❌ Skipped

jobs:
  R-CMD-check:
    
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config: |
          ${{ fromJSON(
          (github.event_name == 'schedule')
          && '[
            {"os":"ubuntu-latest","r":"release"}
          ]'
          || ((github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'test')
          && '[
            {"os":"ubuntu-latest","r":"devel","http-user-agent":"release"},
            {"os":"ubuntu-latest","r":"release"},
            {"os":"ubuntu-latest","r":"oldrel-1"},
            {"os":"windows-latest","r":"release"},
            {"os":"macos-latest","r":"release"}
          ]'
          || '[
            {"os":"ubuntu-latest","r":"devel","http-user-agent":"release"},
            {"os":"ubuntu-latest","r":"release"},
            {"os":"ubuntu-latest","r":"oldrel-1"}
          ]')
          ) }}
      


    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      BRANCH_NAME: ${{ github.ref_name }}
      EVENT_NAME: ${{ github.event_name }}

    steps:
      - name: Greet the user
        run: echo branch "$BRANCH_NAME" event "$EVENT_NAME"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
